version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend/data:/app/data
    environment:
      - DB_FILE=/app/data/events.db

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - VITE_API_BASE=http://backend:4000
    depends_on:
      - backend
